const SELECTION_OVERLAY_SELECTOR = '.selected-entity-hud-overlay';

function localHeroIsSelected() {
  const overlay = document.querySelector<HTMLElement>(SELECTION_OVERLAY_SELECTOR);
  return Boolean(overlay?.hidden);
}

export function mountHeroFunctionKeyControls() {
  let suppressSyntheticCameraFocus = false;
  let clearSuppressionTimer = 0;

  const clearSuppression = () => {
    suppressSyntheticCameraFocus = false;
    if (clearSuppressionTimer) {
      window.clearTimeout(clearSuppressionTimer);
      clearSuppressionTimer = 0;
    }
  };

  const onKeyDownCapture = (event: KeyboardEvent) => {
    if (event.code === 'F1') {
      if (event.repeat) {
        event.preventDefault();
        event.stopImmediatePropagation();
        return;
      }

      // Snapshot the selection state BEFORE the game's own F1 handler runs.
      // If Alden was not already selected, allow F1 to select him but suppress every
      // synthetic Space generated by selection listeners during this whole dispatch.
      // Keeping suppression alive until the next task also covers duplicate listeners
      // that can briefly coexist under React Strict Mode/HMR.
      clearSuppression();
      suppressSyntheticCameraFocus = !localHeroIsSelected();
      if (suppressSyntheticCameraFocus) {
        clearSuppressionTimer = window.setTimeout(() => {
          suppressSyntheticCameraFocus = false;
          clearSuppressionTimer = 0;
        }, 0);
      }
      return;
    }

    if (
      event.code !== 'Space'
      || !suppressSyntheticCameraFocus
      || event.isTrusted
    ) return;

    event.preventDefault();
    event.stopImmediatePropagation();
  };

  window.addEventListener('keydown', onKeyDownCapture, true);

  return () => {
    clearSuppression();
    window.removeEventListener('keydown', onKeyDownCapture, true);
  };
}
